import random

print('Choose one of the templates')

templates = input('enter 1, 2 or 3: ') or random.choice(['1','2','3'])

if templates == '1':
    number = input('Input a number: ')
    time = input('Measure of time: ')
    transport = input('Input mode of transport: ')
    adjective1 = input('Input adjective: ') 
    adjective2 = input('Input adjective again: ')
    noun = input('Input noun: ')
    color = input('Input color: ')
    body = input('Input part of the body: ')
    verb = input('Input verb: ')  
    number2 = input('Input a number again: ')
    noun2 = input('Input noun again: ')
    noun3 = input('Input noun again: ')
    body2 = input('Input part of the body again: ')
    verb2 = input('Input verb again: ')
    noun4 = input('Input noun again: ')
    adjective3 = input('Input adjective again: ')
    word = input('Input a silly word: ')
    noun5 = input('Input noun again: ')

    print(f"It was about {number} {time} ago when I arrived at the hospital in a {transport}.")
    print(f"The hospital is a/an {adjective1} place, there are a lot of {adjective2} {noun} here.")
    print(f"There are nurses here who have {color} {body}.")
    print(f"If someone wants to come into my room I told them that they have to {verb} first.")
    print(f"I’ve decorated my room with {number2} {noun2}.")
    print(f"Today I talked to a doctor and they were wearing a {noun3} on their {body2}.")
    print(f"I heard that all doctors {verb2} {noun4} every day for breakfast.")
    print(f"The most {adjective3} thing about being in the hospital is the {word} {noun5}!")


elif templates == '2':
    name = input('Input name: ')
    noun = input('Input a noun: ')
    feeling = input('Input feeling: ')
    verb = input('Input verb: ') 
    feeling2 = input('Input feeling again: ')
    animal = input('Input animal: ')
    verb2 = input('Input verb again: ')
    color = input('Input a color: ')
    verb3 = input('Input a verb + ing: ')
    adverb = input('Input an adverb + ly: ')
    number = input('Input number: ')
    time = input('Measure of time: ')
    color2 = input('Input color again: ')
    animal2 = input('Input animal again: ')
    number2 = input('Input number again: ')
    word = input('Input silly word: ')
    noun2 = input('Input noun again: ')

    print(f"This weekend I am going camping with {name}.")
    print(f"I packed my lantern, sleeping bag, and {noun}.")
    print(f"I am so {feeling} to {verb} in a tent.")
    print(f"I am {feeling2} we might see a(n) {animal}, I hear they’re kind of dangerous.")
    print(f"While we’re camping, we are going to hike, fish, and {verb2}.")
    print(f"I have heard that the {color} lake is great for {verb3}.")
    print(f"Then we will {adverb} hike through the forest for {number} {time}.")
    print(f"If I see a {color2} {animal2} while hiking, I am going to bring it home as a pet!")
    print(f"At night we will tell {number2} {word} stories and roast {noun2} around the campfire!!")

elif templates == '3': 
    name = input('Input name: ')
    adjective = input('Input adjective: ')
    color = input('Input a color: ')
    animal = input('Input an animal: ')
    place = input('Input a place: ')
    adjective2 = input('Input adjective again: ')
    magical_creature = input('Input magical plural: ')
    adjective3 = input('Input adjective again: ')
    magical_creature2 = input('Input magical (plural) again: ')
    room = input('Input room in house: ')
    noun = input('Input a noun: ')
    noun2 = input('Input a noun again: ')
    noun3 = input('Input a noun (plural) again: ')
    adjective4 = input('Input adjective again: ')
    noun4 = input('Input a noun (plural) again: ')
    number = input('Input a number: ')
    time = input('Measure of time: ')
    verb = input('Input a verb + ing: ')
    adjective5 = input('Input adjective again: ')
    noun5 = input('Input a noun again: ')

    print(f"Dear {name},")
    print(f"I am writing to you from a {adjective} castle in an enchanted forest.")
    print(f"I found myself here one day after going for a ride on a {color} {animal} in {place}.")
    print(f"There are {adjective2} {magical_creature} and {adjective3} {magical_creature2} here!")
    print(f"In the {room}, there is a pool full of {noun}.")
    print(f"I fall asleep each night on a {noun2} of {noun3} and dream of {adjective4} {noun4}.")
    print(f"It feels as though I have lived here for {number} {time}.")
    print(f"I hope one day you can visit, although the only way to get here now is {verb} on a {adjective5} {noun5}!!")

else: 
    print(f"Invalid input. Please enter 1, 2, or 3")
